### ISSUE TITLE
Groups: pad encrypted key list size

### ISSUE THREAD

**Issue by jagerman** [oxen-io/libsession-util#45]
Our list of group encryption keys won't be entirely encrypted: anyone will be able to read that it is a list of encrypted keys (but inside that each key is encrypted).

This leaks the group size.  We can fix it easily, though, by appending dummy values to pad it out to the nearest increment of some multiple (maybe 64; will need to think about the final sizes) so that it doesn't directly leak the group size.

**Comment by jagerman** [comment]
(Thanks to @venezuela01 for suggesting this to me out-of-band)

**Comment by frtget** [comment]
It seems I have missed some information about the new closed groups design. Where can I read more about this ?

**Comment by jagerman** [comment]
This is done (in the merged version of #42).
